name: FreeRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 99999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Syamsul37/rdp1/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Syamsul37/rdp1/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/Syamsul37/rdp1/main/wallpaper.bat -OutFile wallpaper.bat
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe config add-authtoken 1wGbGexmlyZmGmbxZpzLQSJIr9O_4fAHRY7f6sJtoMUok3Uac
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: jajal ngorok
      run: .\ngrok\ngrok.exe tcp -region ap 3389
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.jpg D:\a\wallpaper.jpg
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp -region ap 3389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://github.com/Syamsul37/rdp1/raw/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
